
export default new Map([
["src/content/blog/essay-editing-checklist.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fessay-editing-checklist.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-plan-a-realistic-masters-thesis-timeline.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-plan-a-realistic-masters-thesis-timeline.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-write-a-masters-thesis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-write-a-masters-thesis.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-write-a-rebuttal-in-an-argumentative-essay.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-write-a-rebuttal-in-an-argumentative-essay.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-write-a-research-paper-without-plagiarism.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-write-a-research-paper-without-plagiarism.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-write-an-essay-as-a-university-student.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-write-an-essay-as-a-university-student.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-write-an-msc-dissertation.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-write-an-msc-dissertation.mdx&astroContentModuleFlag=true")],
["src/content/blog/masters-thesis-structure-example.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fmasters-thesis-structure-example.mdx&astroContentModuleFlag=true")]]);
		